nodemcu-tool.cmd upload ^
src\$version.txt ^
src\apds9960.lua ^
src\brewNode.lua ^
src\breweryNode.lua ^
src\buttonNode.lua ^
src\credential.lua ^
src\deepsleep.lua ^
src\electricityNode.lua ^
src\espConfig.lua ^
src\garageNode.lua ^
src\gestureNode.lua ^
src\httpDL.lua ^
src\i2ctool.lua ^
src\ledNode.lua ^
src\mpu6050.lua ^
src\mqttNode.lua ^
src\mqttNodeConfig.lua ^
src\mqttNodeConnect.lua ^
src\mqttNodeUpdate.lua ^
src\noNode.lua ^
src\oledNode.lua ^
src\pixel.lua ^
src\pixelNode.lua ^
src\pixelNodeConnect.lua ^
src\pixelNodeMessage.lua ^
src\poolNode.lua ^
src\relayNode.lua ^
src\rfNode.lua ^
src\rgbNode.lua ^
src\sonoffNode.lua ^
src\spindleNode.lua ^
src\ssrNode.lua ^
src\startup.lua ^
src\tempNode.lua ^
src\trace.lua ^
src\update.lua ^
src\updateCompletion.lua ^
src\updateFailure.lua ^
src\updateFiles.lua ^
src\updateMqttState.lua ^
src\updateWifi.lua ^
src\util.lua ^
src\xmasNode.lua ^
src\_init.lua
