nodemcu-tool.cmd upload ^
bin\apds9960.lc ^
bin\apds9960debug.lc ^
bin\brewNode.lc ^
bin\buttonNode.lc ^
bin\credential.lc ^
bin\ds18b20.lc ^
bin\espConfig.lc ^
bin\garageNode.lc ^
bin\gestureNode.lc ^
bin\httpDL.lc ^
bin\i2ctool.lc ^
bin\ledNode.lc ^
bin\mpu6050.lc ^
bin\mqttNode.lc ^
bin\mqttNodeConfig.lc ^
bin\mqttNodeConnect.lc ^
bin\mqttNodeUpdate.lc ^
bin\noNode.lc ^
bin\oledNode.lc ^
bin\poolNode.lc ^
bin\relayNode.lc ^
bin\rfNode.lc ^
bin\sonoffNode.lc ^
bin\spindleNode.lc ^
bin\startup.lc ^
bin\tempNode.lc ^
bin\trace.lc ^
bin\update.lc ^
bin\updateCompletion.lc ^
bin\updateFailure.lc ^
bin\updateFiles.lc ^
bin\updateMqttState.lc ^
bin\updateWifi.lc ^
bin\util.lc ^
bin\xmasNode.lc
